### PR TITLE
Added mongodb document store adapter

### PR DESCRIPTION
**Pull request by Roundaround**

### CODE REVIEW

**Comment by zneix** [comment]
Can this be merged? Would be super cool to have an option to integrate my hastebin server with already existing database, thanks!

**Comment by seejohnrun** [comment]
Thank you!

**Comment by Roundaround** [comment]
Lol wow gotta say, never thought I'd get notified of someone merging my 4 year old PR. Hopefully everything still works with the latest MongoDB implementation?

**Comment by seejohnrun** [comment]
Well here we are :) thank you for your contribution @Roundaround

**Pull request merged**
