### PR TITLE
Dockerize hastebin

### PR DESCRIPTION
**Pull request by ekristen**
docker is a pretty cool new technology, I've update this app to build a docker image. I've also updated the app to use node-config, which allows for loading different config files based on hostname, node environment, etc. 

If you accept the PR anyone who updates will have to redo their config slightly by moving it into the config folder and modifying it to look like default.js, except with their values.

If you accept the PR, you can setup a trusted build on index.docker.io to build hastebin image automatically, since you are the author, I left that for you.

How to build docker image for testing

```
docker build -t hastebin .
```

Download redis into docker

```
docker pull dockerfile/redis
```

Start the stack

```
docker run -d --name="hastebin_redis" dockerfile/redis
docker run -d --name="hastebin" -p 7777:7777 -link hastebin_redis:redis hastebin
```

### CODE REVIEW

**Comment by frdmn** [comment]
I did a combination out of both of our version, including a pretty easy make file to rebuild and restart the container/instances:

https://github.com/frdmn/docker-hastebin

**Comment by bentenz5** [comment]
I dont like docker personally. I'll just stick to straight up, good old nodejs ;p

**Comment by alazymeme** [comment]
Be good if this was merged

**Comment by seejohnrun** [comment]
Thank you / I've recently merged a Dockerfile implementation

**Pull request closed without merging**
